Added configuration parameter lockDir to specify where proto.lock lives
salesforce/proto-backwards-compat-maven-plugin pull request #16
Opened 2019-08-13 16:31 UTC by seime

Passing `<option>--lockdir=somewhere_else</option>` does not work, the plugin always checks the proto root directory for `proto.lock` .

This PR adds a new configuration parameter `lockDir`

2019-08-14 01:48 UTC, rmichela requested changes
I'm curious, what prompted the need for this change?

2019-08-14 01:48 UTC, rmichela commented on src/main/java/com/salesforce/servicelibs/BackwardsCompatibilityCheckMojo.java
> +            if (options.toUpperCase().contains("--LOCKDIR")) {
Move this new code section to a private method that returns the `lockDir`.  It's not your fault that `execute()` is getting really hairy, but it's time to start breaking it into methods.

2019-08-14 01:48 UTC, rmichela commented on src/main/java/com/salesforce/servicelibs/BackwardsCompatibilityCheckMojo.java
> +            String _lockDir = null;
nit: There has to be a better variable name than `_lockDir`.

2019-08-14 07:56 UTC, seime commented
> I'm curious, what prompted the need for this change?

We generate some proto descriptors from xml schema, and as with all generated sources/resources we place them in the (maven) target folder before packaging and deploying them as jar files.

The plugin was hardcoded to always look for proto.lock inside the proto source folder, and if not found it would just renitialize a new proto.lock there each time. Even if --lockdir would be specified the maven plugin wouldn't honour that and just renitialize a new proto.lock inside the temp folder. This caused changes silently to be accepted (except for a log statement saying that it was initialized)

2019-08-14 12:46 UTC, rmichela approved these changes
Thanks for the extra refactoring!

2019-08-14 12:46 UTC, merged

2021-01-28 19:02 UTC, rmichela commented
Released in [1.0.6](https://github.com/salesforce/proto-backwards-compat-maven-plugin/releases/tag/v1.0.6)